import 'package:flutter/foundation.dart';

/// Centralized configuration for the BioPay Zero-Knowledge Pipeline.
/// 
/// Contains threshold bounds, ML configurations, and biometric matching
/// distances mapped to the underlying pgvector indexing.
abstract final class BiopayConstants {
  // ── Environment ──────────────────────────────────────────────────────────

  /// Determines if the current environment requires strict TFLite embeddings
  /// or pseudo-random fallbacks for simulator testing.
  static bool get isSimulator => kDebugMode && TargetPlatform.iOS != defaultTargetPlatform && !kIsWeb; // Simple heuristic

  // ── Face Detection & Alignment ───────────────────────────────────────────

  /// The minimum confidence score for a face to be considered valid 
  /// by MLKit Face Detection.
  static const double minFaceTrackingProbability = 0.85;

  /// Maximum allowed roll angle (z-axis rotation) for a valid scan.
  static const double maxFaceRollAngle = 12.0;

  /// Maximum allowed yaw angle (y-axis rotation) for a valid scan.
  static const double maxFaceYawAngle = 12.0;

  /// Minimum probability for the left eye being open.
  static const double minEyeOpenProbability = 0.50;

  /// The number of required sequential frames for liveness detection
  /// during enrollment (preventing static images).
  static const int requiredEnrollmentSamples = 5;

  // ── Matrix / Embedding Generation ────────────────────────────────────────

  /// Size of the output vector generated by our chosen MobileFaceNet model.
  static const int embeddingVectorSize = 512;

  /// The minimum L2 distance distance threshold to pass facial recognition 
  /// (mapping pgvector Euclidean distance `v1 <-> v2`). Lower means closer.
  static const double confidenceThresholdL2 = 1.15; 

  /// Cosine similarity threshold (`1 - (v1 <=> v2)` in pgvector).
  static const double confidenceThresholdCosine = 0.85;

  // ── Timeouts & Limits ──────────────────────────────────────────────────

  /// Maximum duration the camera pipeline will run before failing out
  /// to prevent overheating and battery drain.
  static const Duration maxScanDuration = Duration(seconds: 45);

  /// Interval between capturing valid geometry frames.
  static const Duration sampleCaptureInterval = Duration(milliseconds: 300);
}
