export const parserSchemaVersion = "collect.sms_parser.v1";

export const smsParserJsonSchema = {
  type: "object",
  additionalProperties: false,
  properties: {
    is_mobile_money_payment: { type: "boolean" },
    network: { type: "string", enum: ["mtn_momo", "airtel_money", "unknown"] },
    direction: { type: "string", enum: ["incoming", "outgoing", "unknown"] },
    amount_rwf: { type: ["integer", "null"] },
    currency: { type: "string", enum: ["RWF", "unknown"] },
    transaction_id: { type: ["string", "null"] },
    sender_name: { type: ["string", "null"] },
    sender_phone: { type: ["string", "null"] },
    receiver_name: { type: ["string", "null"] },
    receiver_phone: { type: ["string", "null"] },
    transaction_time: { type: ["string", "null"] },
    message_language: { type: "string", enum: ["en", "rw", "fr", "unknown"] },
    raw_reference: { type: ["string", "null"] },
    detected_collection_code: { type: ["string", "null"] },
    detected_user_public_id: { type: ["string", "null"] },
    balance_mentioned: { type: "boolean" },
    fees_mentioned: { type: "boolean" },
    confidence: { type: "number", minimum: 0, maximum: 1 },
    explanation: { type: "string" },
  },
  required: [
    "is_mobile_money_payment",
    "network",
    "direction",
    "amount_rwf",
    "currency",
    "transaction_id",
    "sender_name",
    "sender_phone",
    "receiver_name",
    "receiver_phone",
    "transaction_time",
    "message_language",
    "raw_reference",
    "detected_collection_code",
    "detected_user_public_id",
    "balance_mentioned",
    "fees_mentioned",
    "confidence",
    "explanation",
  ],
} as const;
