org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel=false
org.gradle.workers.max=1
org.gradle.daemon=false
android.useAndroidX=true
kotlin.compiler.execution.strategy=in-process
kotlin.daemon.jvmargs=-Xmx2G
kotlin.incremental=false
kotlin.incremental.useClasspathSnapshot=false
