export const parsedSmsJsonSchema = {
  type: "object",
  additionalProperties: false,
  properties: {
    parse_status: {
      type: "string",
      enum: ["parsed", "needs_review", "failed"],
    },
    confidence: {
      type: "number",
      minimum: 0,
      maximum: 1,
    },
    tx_direction: {
      type: "string",
      enum: ["credit", "debit", "unknown"],
    },
    tx_type: { type: "string" },
    tx_category: { type: "string" },
    cashflow_bucket: {
      type: "string",
      enum: [
        "income",
        "expense",
        "savings",
        "transfer",
        "loan",
        "fees",
        "unknown",
      ],
    },
    momo_tx_id: { type: ["string", "null"] },
    amount: { type: ["integer", "null"] },
    currency: { type: "string" },
    tx_date: { type: ["string", "null"] },
    tx_time: { type: ["string", "null"] },
    tx_datetime_iso: { type: ["string", "null"] },
    payer_name: { type: ["string", "null"] },
    payer_number_last3: { type: ["string", "null"] },
    payer_number_full: { type: ["string", "null"] },
    payee_name: { type: ["string", "null"] },
    payee_number_or_code: { type: ["string", "null"] },
    merchant_code: { type: ["string", "null"] },
    fee_amount: { type: ["integer", "null"] },
    balance_after: { type: ["integer", "null"] },
    counterparty_name: { type: ["string", "null"] },
    ai_summary: { type: ["string", "null"] },
    recurring_pattern_hint: {
      type: "string",
      enum: ["recurring", "seasonal", "one_off", "unknown"],
    },
    narrative: { type: ["string", "null"] },
    notes: { type: ["string", "null"] },
  },
  required: [
    "parse_status",
    "confidence",
    "tx_direction",
    "tx_type",
    "tx_category",
    "cashflow_bucket",
    "momo_tx_id",
    "amount",
    "currency",
    "tx_date",
    "tx_time",
    "tx_datetime_iso",
    "payer_name",
    "payer_number_last3",
    "payer_number_full",
    "payee_name",
    "payee_number_or_code",
    "merchant_code",
    "fee_amount",
    "balance_after",
    "counterparty_name",
    "ai_summary",
    "recurring_pattern_hint",
    "narrative",
    "notes",
  ],
};
