grant execute on function admin_current_user() to authenticated;
grant execute on function admin_overview() to authenticated;
grant execute on function admin_list_public_requests(text, text) to authenticated;
grant execute on function admin_list_collections(text, text) to authenticated;
grant execute on function admin_list_users(text, text) to authenticated;
grant execute on function admin_list_payment_events(text, text) to authenticated;
grant execute on function admin_list_unallocated(text, text) to authenticated;
grant execute on function admin_list_payments(text, text) to authenticated;
grant execute on function admin_list_ledger(text, text) to authenticated;
grant execute on function admin_list_receivers(text, text) to authenticated;
grant execute on function admin_list_sms_metadata(text, text) to authenticated;
grant execute on function admin_list_audit_logs(text, text) to authenticated;
grant execute on function admin_get_collection(uuid) to authenticated;
grant execute on function admin_get_user(uuid) to authenticated;
grant execute on function admin_get_payment(uuid) to authenticated;
grant execute on function admin_get_payment_event(uuid) to authenticated;
grant execute on function admin_get_receiver(uuid) to authenticated;
grant execute on function admin_get_sms_metadata(uuid) to authenticated;
grant execute on function admin_system_health(text) to authenticated;
